/*
 * Project: RooFit
 * Authors:
 *   Jonas Rembser, CERN 2026
 *
 * Copyright (c) 2026, CERN
 *
 * Redistribution and use in source and binary forms,
 * with or without modification, are permitted according to the terms
 * listed in LICENSE (http://roofit.sourceforge.net/license.txt)
 */

#include <RooFit/Detail/BuiltinClad.h>

#include <TInterpreter.h>

#include <dlfcn.h>

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <mutex>
#include <unordered_map>
#include <sstream>
#include <stdexcept>
#include <unistd.h>

namespace fs = std::filesystem;

namespace RooFit::Detail::BuiltinClad {

namespace {

std::string quote(std::string const &s)
{
   return "\"" + s + "\"";
}

/// The directory of libRooFitClad, which in the install tree is also where the
/// plugin is, and next to the headers.
std::string libraryDir()
{
   Dl_info info;
   if (dladdr(reinterpret_cast<void *>(&libraryDir), &info) && info.dli_fname) {
      return fs::path(info.dli_fname).parent_path().string();
   }
   return {};
}

bool isCladIncludeDir(fs::path const &dir)
{
   // Version.inc is generated by the build, so its presence tells that the
   // directory is a complete set of headers and not only the source tree.
   return fs::exists(dir / "clad" / "Differentiator" / "Differentiator.h") &&
          fs::exists(dir / "clad" / "Differentiator" / "Version.inc");
}

/// The working directory, created on first use and removed at exit unless the
/// user named it.
class WorkDir {
public:
   WorkDir()
   {
      if (const char *env = std::getenv("ROOFIT_CLAD_WORKDIR"); env && *env) {
         _path = env;
         _remove = false;
      } else {
         _path = (fs::temp_directory_path() / ("roofit-clad-" + std::to_string(getpid()))).string();
         _remove = true;
      }
      fs::create_directories(_path);
   }
   ~WorkDir()
   {
      if (_remove) {
         std::error_code ec;
         fs::remove_all(_path, ec);
      }
   }
   std::string const &path() const { return _path; }

private:
   std::string _path;
   bool _remove = false;
};

} // namespace

std::string const &compiler()
{
   static const std::string path = ROOFIT_CLAD_COMPILER;
   return path;
}

std::string const &pluginPath()
{
   static const std::string path = [] {
      fs::path installed = fs::path(libraryDir()) / ROOFIT_CLAD_PLUGIN_FILE;
      return fs::exists(installed) ? installed.string() : std::string(ROOFIT_CLAD_PLUGIN);
   }();
   return path;
}

std::vector<std::string> const &includeDirs()
{
   static const std::vector<std::string> dirs = [] {
      std::vector<std::string> out;
      fs::path installed = fs::path(libraryDir()).parent_path() / "include";
      if (isCladIncludeDir(installed)) {
         out.push_back(installed.string());
         return out;
      }
      std::stringstream ss{ROOFIT_CLAD_INCLUDE_DIRS};
      for (std::string dir; std::getline(ss, dir, ':');) {
         out.push_back(dir);
      }
      return out;
   }();
   return dirs;
}

std::string const &workDir()
{
   static const WorkDir dir;
   return dir.path();
}

std::string compileCommand(std::string const &source, std::string const &output)
{
   std::stringstream cmd;
   cmd << quote(compiler()) << " -std=c++" << ROOFIT_CLAD_CXX_STANDARD << " -O2 -g -fPIC -shared"
       << " -fvisibility=hidden -fvisibility-inlines-hidden";
#ifdef __APPLE__
   // Like for ACLiC: the code calls into libraries that are already loaded.
   cmd << " -undefined dynamic_lookup";
#endif
   cmd << " -fplugin=" << quote(pluginPath())
       << " -Xclang -plugin-arg-clad -Xclang -fgenerated-source-dir=" << workDir();
   for (std::string const &dir : includeDirs()) {
      cmd << " -I" << quote(dir);
   }
   // The include path of the interpreter, in the form -I"dir" -I"dir" ...
   cmd << " " << gInterpreter->GetIncludePath();
   if (const char *extra = std::getenv("ROOFIT_CLAD_EXTRA_FLAGS")) {
      cmd << " " << extra;
   }
   cmd << " " << quote(source) << " -o " << quote(output);
   return cmd.str();
}

Library::Library(std::string const &name, std::string const &code)
{
   fs::path dir = workDir();
   _sourcePath = (dir / (name + ".cxx")).string();
   _path = (dir / (name + ".so")).string();
   std::string logPath = (dir / (name + ".log")).string();

   {
      std::ofstream out{_sourcePath};
      out << code;
   }

   _command = compileCommand(_sourcePath, _path) + " > " + quote(logPath) + " 2>&1";
   int status = std::system(_command.c_str());

   {
      std::ifstream log{logPath};
      std::stringstream ss;
      ss << log.rdbuf();
      _compilerOutput = ss.str();
   }

   if (status != 0) {
      std::stringstream msg;
      msg << "The builtin clad could not compile " << _sourcePath << ". The compiler says:\n"
          << _compilerOutput << "\nThe command was:\n"
          << _command << "\n";
      throw std::runtime_error(msg.str());
   }

   _handle = dlopen(_path.c_str(), RTLD_NOW | RTLD_LOCAL);
   if (!_handle) {
      throw std::runtime_error("The builtin clad could not load " + _path + ": " + dlerror());
   }
}

Library::~Library()
{
   if (_handle) {
      dlclose(_handle);
   }
}

std::shared_ptr<Library> Library::compile(std::string const &name, std::string const &code)
{
   static std::mutex mutex;
   static std::unordered_map<std::string, std::shared_ptr<Library>> cache;
   std::lock_guard<std::mutex> guard{mutex};
   auto &lib = cache[code];
   if (!lib) {
      lib = std::make_shared<Library>(name, code);
   }
   return lib;
}

void *Library::symbol(std::string const &symbolName) const
{
   return _handle ? dlsym(_handle, symbolName.c_str()) : nullptr;
}

void *Library::entryPoint(std::string const &name) const
{
   auto func = reinterpret_cast<void *(*)()>(symbol(name));
   if (!func) {
      throw std::runtime_error("The builtin clad found no exported function " + name + " in " + _path);
   }
   return func();
}

} // namespace RooFit::Detail::BuiltinClad
