/*
 * Project: RooFit
 * Authors:
 *   Jonas Rembser, CERN 2026
 *
 * Copyright (c) 2026, CERN
 *
 * Redistribution and use in source and binary forms,
 * with or without modification, are permitted according to the terms
 * listed in LICENSE (http://roofit.sourceforge.net/license.txt)
 */

#include <RooFit/Detail/BuiltinClad.h>

#include <TInterpreter.h>

#include <dlfcn.h>

#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <mutex>
#include <unordered_map>
#include <sstream>
#include <stdexcept>
#include <unistd.h>

namespace fs = std::filesystem;

namespace RooFit::Detail::BuiltinClad {

namespace {

std::string quote(std::string const &s)
{
   return "\"" + s + "\"";
}

/// The directory of libRooFitClad, which in the install tree is also where the
/// plugin is, and next to the headers.
std::string libraryDir()
{
   Dl_info info;
   if (dladdr(reinterpret_cast<void *>(&libraryDir), &info) && info.dli_fname) {
      return fs::path(info.dli_fname).parent_path().string();
   }
   return {};
}

bool isCladIncludeDir(fs::path const &dir)
{
   // Version.inc is generated by the build, so its presence tells that the
   // directory is a complete set of headers and not only the source tree.
   return fs::exists(dir / "clad" / "Differentiator" / "Differentiator.h") &&
          fs::exists(dir / "clad" / "Differentiator" / "Version.inc");
}

/// The code without its comments, and with each run of whitespace outside of
/// literals reduced to a single space. The compile cache is keyed on this, so
/// that code that differs only in comments compiles to the same library:
/// RooFit's codegen writes the current values of the nodes into comments, and
/// those change from fit to fit while the code stays the same. String and
/// character literals are kept as they are, including raw string literals
/// (only with the plain R prefix: an encoding prefix like u8R is not
/// recognized).
std::string cacheKey(std::string const &code)
{
   const std::size_t n = code.size();
   std::string out;
   out.reserve(n);
   std::size_t i = 0;
   auto isIdentifierChar = [](char c) { return std::isalnum(static_cast<unsigned char>(c)) || c == '_'; };
   auto addSpace = [&out] {
      if (!out.empty() && out.back() != ' ') {
         out += ' ';
      }
   };
   while (i < n) {
      const char c = code[i];
      if (std::isspace(static_cast<unsigned char>(c))) {
         addSpace();
         ++i;
         continue;
      }
      if (c == 'R' && i + 1 < n && code[i + 1] == '"' && (i == 0 || !isIdentifierChar(code[i - 1]))) {
         std::size_t open = code.find('(', i + 2);
         if (open != std::string::npos) {
            std::string close = ")" + code.substr(i + 2, open - i - 2) + "\"";
            std::size_t end = code.find(close, open + 1);
            if (end != std::string::npos) {
               end += close.size();
               out.append(code, i, end - i);
               i = end;
               continue;
            }
         }
      }
      if (c == '"' || c == '\'') {
         std::size_t j = i + 1;
         while (j < n && code[j] != c && code[j] != '\n') {
            if (code[j] == '\\') {
               ++j;
            }
            ++j;
         }
         j = std::min(j + 1, n);
         out.append(code, i, j - i);
         i = j;
         continue;
      }
      if (c == '/' && i + 1 < n && code[i + 1] == '/') {
         i = code.find('\n', i);
         if (i == std::string::npos) {
            break;
         }
         continue;
      }
      if (c == '/' && i + 1 < n && code[i + 1] == '*') {
         i = code.find("*/", i + 2);
         if (i == std::string::npos) {
            break;
         }
         i += 2;
         addSpace();
         continue;
      }
      out += c;
      ++i;
   }
   if (!out.empty() && out.back() == ' ') {
      out.pop_back();
   }
   return out;
}

/// Runs the compiler command, with its output going to `logPath`, and returns
/// the output. Throws std::runtime_error with the output if the command fails.
std::string runCompiler(std::string const &command, std::string const &logPath, std::string const &what)
{
   int status = std::system((command + " > " + quote(logPath) + " 2>&1").c_str());

   std::ifstream log{logPath};
   std::stringstream ss;
   ss << log.rdbuf();
   std::string output = ss.str();

   if (status != 0) {
      std::stringstream msg;
      msg << "The builtin clad could not compile " << what << ". The compiler says:\n"
          << output << "\nThe command was:\n"
          << command << "\n";
      throw std::runtime_error(msg.str());
   }
   return output;
}

/// The working directory, created on first use and removed at exit unless the
/// user named it.
class WorkDir {
public:
   WorkDir()
   {
      if (const char *env = std::getenv("ROOFIT_CLAD_WORKDIR"); env && *env) {
         _path = env;
         _remove = false;
      } else {
         _path = (fs::temp_directory_path() / ("roofit-clad-" + std::to_string(getpid()))).string();
         _remove = true;
      }
      fs::create_directories(_path);
   }
   ~WorkDir()
   {
      if (_remove) {
         std::error_code ec;
         fs::remove_all(_path, ec);
      }
   }
   std::string const &path() const { return _path; }

private:
   std::string _path;
   bool _remove = false;
};

} // namespace

std::string const &compiler()
{
   static const std::string path = ROOFIT_CLAD_COMPILER;
   return path;
}

std::string const &pluginPath()
{
   static const std::string path = [] {
      fs::path installed = fs::path(libraryDir()) / ROOFIT_CLAD_PLUGIN_FILE;
      return fs::exists(installed) ? installed.string() : std::string(ROOFIT_CLAD_PLUGIN);
   }();
   return path;
}

std::vector<std::string> const &includeDirs()
{
   static const std::vector<std::string> dirs = [] {
      std::vector<std::string> out;
      fs::path installed = fs::path(libraryDir()).parent_path() / "include";
      if (isCladIncludeDir(installed)) {
         out.push_back(installed.string());
         return out;
      }
      std::stringstream ss{ROOFIT_CLAD_INCLUDE_DIRS};
      for (std::string dir; std::getline(ss, dir, ':');) {
         out.push_back(dir);
      }
      return out;
   }();
   return dirs;
}

std::string const &workDir()
{
   static const WorkDir dir;
   return dir.path();
}

namespace {

/// The compiler with the flags that both the libraries and the precompiled
/// headers are compiled with. The two have to match, or clang rejects the
/// precompiled header.
std::string compilerWithFlags()
{
   std::stringstream cmd;
   cmd << quote(compiler()) << " -std=c++" << ROOFIT_CLAD_CXX_STANDARD << " -O2 -g -fPIC"
       << " -fvisibility=hidden -fvisibility-inlines-hidden";
   cmd << " -fplugin=" << quote(pluginPath())
       << " -Xclang -plugin-arg-clad -Xclang -fgenerated-source-dir=" << workDir();
   for (std::string const &dir : includeDirs()) {
      cmd << " -I" << quote(dir);
   }
   // The include path of the interpreter, in the form -I"dir" -I"dir" ...
   cmd << " " << gInterpreter->GetIncludePath();
   if (const char *extra = std::getenv("ROOFIT_CLAD_EXTRA_FLAGS")) {
      cmd << " " << extra;
   }
   return cmd.str();
}

} // namespace

std::string compileCommand(std::string const &source, std::string const &output, std::string const &pch)
{
   std::stringstream cmd;
   cmd << compilerWithFlags() << " -shared";
#ifdef __APPLE__
   // Like for ACLiC: the code calls into libraries that are already loaded.
   cmd << " -undefined dynamic_lookup";
#endif
   if (!pch.empty()) {
      cmd << " -include-pch " << quote(pch);
   }
   cmd << " " << quote(source) << " -o " << quote(output);
   return cmd.str();
}

std::string precompileCommand(std::string const &header, std::string const &output)
{
   return compilerWithFlags() + " -x c++-header " + quote(header) + " -o " + quote(output);
}

PrecompiledHeader::PrecompiledHeader(std::string const &name, std::string const &code)
{
   fs::path dir = workDir();
   _headerPath = (dir / (name + ".h")).string();
   _path = (dir / (name + ".pch")).string();
   std::string logPath = (dir / (name + ".pch.log")).string();

   {
      std::ofstream out{_headerPath};
      // The sources include the header again, see Library::Library(), which
      // the pragma turns into a no-op: the precompiled header remembers it.
      out << "#pragma once\n" << code;
   }

   _command = precompileCommand(_headerPath, _path);
   _compilerOutput = runCompiler(_command, logPath, _headerPath);
}

std::shared_ptr<PrecompiledHeader> PrecompiledHeader::compile(std::string const &name, std::string const &code)
{
   static std::mutex mutex;
   static std::unordered_map<std::string, std::shared_ptr<PrecompiledHeader>> cache;
   std::lock_guard<std::mutex> guard{mutex};
   auto &pch = cache[cacheKey(code)];
   if (!pch) {
      pch = std::make_shared<PrecompiledHeader>(name, code);
   }
   return pch;
}

Library::Library(std::string const &name, std::string const &code, std::shared_ptr<PrecompiledHeader const> pch)
   : _pch{std::move(pch)}
{
   fs::path dir = workDir();
   _sourcePath = (dir / (name + ".cxx")).string();
   _path = (dir / (name + ".so")).string();
   std::string logPath = (dir / (name + ".log")).string();

   {
      std::ofstream out{_sourcePath};
      // The source includes the header of the precompiled header, so that it
      // is complete on its own, for anyone who wants to compile it by hand.
      if (_pch) {
         out << "#include " << quote(_pch->headerPath()) << "\n";
      }
      out << code;
   }

   _command = compileCommand(_sourcePath, _path, _pch ? _pch->path() : std::string{});
   _compilerOutput = runCompiler(_command, logPath, _sourcePath);

   _handle = dlopen(_path.c_str(), RTLD_NOW | RTLD_LOCAL);
   if (!_handle) {
      throw std::runtime_error("The builtin clad could not load " + _path + ": " + dlerror());
   }
}

Library::~Library()
{
   if (_handle) {
      dlclose(_handle);
   }
}

std::shared_ptr<Library>
Library::compile(std::string const &name, std::string const &code, std::shared_ptr<PrecompiledHeader const> pch)
{
   static std::mutex mutex;
   static std::unordered_map<std::string, std::shared_ptr<Library>> cache;
   std::lock_guard<std::mutex> guard{mutex};
   std::string key = (pch ? pch->path() : std::string{}) + "\n" + cacheKey(code);
   auto &lib = cache[key];
   if (!lib) {
      lib = std::make_shared<Library>(name, code, std::move(pch));
   }
   return lib;
}

void *Library::symbol(std::string const &symbolName) const
{
   return _handle ? dlsym(_handle, symbolName.c_str()) : nullptr;
}

void *Library::entryPoint(std::string const &name) const
{
   auto func = reinterpret_cast<void *(*)()>(symbol(name));
   if (!func) {
      throw std::runtime_error("The builtin clad found no exported function " + name + " in " + _path);
   }
   return func();
}

} // namespace RooFit::Detail::BuiltinClad
